version: "3.9"

services:
  master_db:
    image: ichiky/woody_master_database:latest
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 30s

  slave_db:
    image: ichiky/woody_slave_database:latest
    cap_add:
      - SYS_NICE
    depends_on:
      - master_db
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 30s
  api:
    image: ichiky/woody_api:latest
    restart: always
    links:
      - "db"
  api2:
    image: ichiky/woody_apisec:latest
    restart: always
    links:
      - "db"
  front:
    image: ichiky/woody_front:latest
    
  redis:
    image: redis:latest
    
  reverse:
    image: ichiky/woody_rp:latest
    ports:
      - "5173:5173"
    depends_on:
      - front
      - api
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    
