version: "3.9"

services:

  dns:
    image: ichiky/dnsserv:1
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  db:
    image: ichiky/woody_database:latest
    cap_add:
      - SYS_NICE  
    restart: always
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'

  api:
    image: ichiky/woody_api:latest
    restart: always
    links:
      - "db"

  front:
    image: ichiky/woody_front:latest
    
  redis:
    image: redis:latest
    
  reverse:
    image: ichiky/woody_rp:latest
    ports:
      - "80:8080"
    depends_on:
      - front
      - api
