version: "3.9"

services:
  db:
    image: ichiky/woody_database:latest
    cap_add:
      - SYS_NICE  
    restart: always
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'

  api:
    image: ichiky/woody_api:latest
    restart: always
    links:
      - "db"
  api:
    image: ichiky/woody_apisec:latest
    restart: always
    links:
      - "db"
  front:
    image: ichiky/woody_front:latest
    
  redis:
    image: redis:latest
    
  reverse:
    image: ichiky/woody_rp:latest
    ports:
      - "5173:5173"
    depends_on:
      - front
      - api
