version: "3.9"

services:

  master_db:
    image: ichiky/woody_master_database:latest
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 30s
    networks:
      - db

  slave_db:
    image: ichiky/woody_slave_database:latest
    cap_add:
      - SYS_NICE
    depends_on:
      - master_db
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 30s
    networks:
      - db

  api:
    image: ichiky/woody_api:latest
    depends_on:
      - redis
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_HOST_MASTER=master_db
      - MYSQL_HOST_SLAVE=slave_db
      - REDIS_HOST=redis
    networks:
      - db
      - api
      - cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/ping"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 20s

  api2:
    image: ichiky/woody_apisec:latest
    depends_on:
      - redis
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_HOST_MASTER=master_db
      - MYSQL_HOST_SLAVE=slave_db
      - REDIS_HOST=redis
    networks:
      - db
      - api
      - cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/ping"]
      interval: 3m
      timeout: 20s
      retries: 3
      start_period: 20s

  front:
    image: ichiky/woody_front:latest
    networks:
      - front

  redis:
    image: redis:6.2-alpine
    networks:
      - cache

  reverse:
    image: ichiky/woody_rp:latest
    ports:
      - "5173:5173"
    depends_on:
      - front
      - api
      - api2
    networks:
      - front
      - api

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  api:
  cache:
  db:
  front:
